use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
target 'CXXTestLib_Example' do
  pod 'CXXTestLib', :path => '../'

  target 'CXXTestLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'JJCodeTestLib'
  end
end
